### ISSUE TITLE
Using Unfolding from Quil

### ISSUE THREAD

**Issue by emanjavacas** [jackrusher/citibikes#1]
I am very interested in getting Unfolding running from Clojure for developing a project in the ink of yours. I am trying to run your project as is in my computer and I am running into several issues. 
In particular, Lein is not able to fetch "glgraphics" and I had to grab "log4j 1.2.17" instead of "1.2.15".
I manage to run the code (removing "glgraphics" from the reps) but nothing but a grey window is being shown. Are there any known incompatibilities of your code with newer versions of "quill" and/or the rest
of the deps?

**Comment by jackrusher** [comment]
I haven't touched that code in a couple of years, but I'll try to have a look in a week or so (after I get back from a trip) to see what's going on.

**Comment by jackrusher** [comment]
Ah, I think I installed glgraphics (a dep of unfolding?) via "lein local", give that a try.

**Comment by emanjavacas** [comment]
Hi! Yes it is, I've downloaded the glgraphics.jar from some website I cannot remember and added it via "localrepo" and now it's working. Thanks!
